openapi: 3.1.0
info:
  title: Movie API
  version: 0.0.1
  description: API for managing movies
servers:
  - url: http://localhost:3001
    description: local development server
components:
  schemas:
    CreateMovieRequest:
      type: object
      properties:
        id:
          type: number
          description: Movie Id
          example: 1
        name:
          type: string
          minLength: 1
          description: Movie name
          example: Inception
        year:
          type: integer
          minimum: 1900
          maximum: 2024
          description: Release year
          example: 2010
        rating:
          type: number
          description: Rating
          example: 7.5
      required:
        - name
        - year
        - rating
    CreateMovieRepsonse:
      type: object
      properties:
        status:
          type: integer
          description: Response status code
          example: 200
        data:
          type: object
          properties:
            id:
              type: number
              description: Movie Id
              example: 1
            name:
              type: string
              minLength: 1
              description: Movie name
              example: Inception
            year:
              type: integer
              minimum: 1900
              maximum: 2024
              description: Release year
              example: 2010
            rating:
              type: number
              description: Rating
              example: 7.5
          required:
            - id
            - name
            - year
            - rating
        error:
          type: string
          description: Error message, if any
      required:
        - status
        - data
    GetMovieResponse:
      type: object
      properties:
        status:
          type: integer
          description: Response status code
          example: 200
        data:
          anyOf:
            - type: object
              properties:
                id:
                  type: number
                  description: Movie Id
                  example: 1
                name:
                  type: string
                  description: Movie name
                  example: Interception
                year:
                  type: number
                  description: Release year
                  example: 2010
                rating:
                  type: number
                  description: Rating
                  example: 7.5
              required:
                - id
                - name
                - year
                - rating
            - type: array
              items:
                type: object
                properties:
                  id:
                    type: number
                    description: Movie Id
                    example: 1
                  name:
                    type: string
                    description: Movie name
                    example: Interception
                  year:
                    type: number
                    description: Release year
                    example: 2010
                  rating:
                    type: number
                    description: Rating
                    example: 7.5
                required:
                  - id
                  - name
                  - year
                  - rating
              description: List of movies or an empty array if no movies exist
            - type: "null"
        error:
          type:
            - string
            - "null"
          description: Error Message if an error occured, otherwise null
      required:
        - status
        - data
    MovieNotFound:
      type: object
      properties:
        status:
          type: integer
          description: Response status code
          example: 404
        error:
          type: string
          description: Error message
          example: Movie not found
      required:
        - status
        - error
    DeleteMovieResponse:
      type: object
      properties:
        status:
          type: integer
          description: Response status code
          example: 200
        message:
          type: string
          description: Success message for the deleted movie
          example: Movie {id} has been deleted
      required:
        - status
        - message
    CreateMovieResponse:
      type: object
      properties:
        status:
          type: integer
          description: Response status code
          example: 200
        data:
          type: object
          properties:
            id:
              type: number
              description: Movie Id
              example: 1
            name:
              type: string
              minLength: 1
              description: Movie name
              example: Inception
            year:
              type: integer
              minimum: 1900
              maximum: 2024
              description: Release year
              example: 2010
            rating:
              type: number
              description: Rating
              example: 7.5
          required:
            - id
            - name
            - year
            - rating
        error:
          type: string
          description: Error message, if any
      required:
        - status
        - data
    Updated movie data:
      type: object
      properties:
        id:
          type: number
          description: Movie id
          example: 1
        name:
          type: string
          description: Movie name
          example: Inception
        year:
          type: number
          description: Release year
          example: 2010
        rating:
          type: number
          description: Rating
          example: 7.5
      required:
        - id
        - name
        - year
        - rating
    UpdatedMovieResponse:
      type: object
      properties:
        status:
          type: integer
          description: Response status code
          example: 200
        data:
          $ref: "#/components/schemas/Updated movie data"
        error:
          type: string
          description: "Error message, if any "
      required:
        - status
        - data
    UpdateMovieRequest:
      type: object
      properties:
        id:
          type: integer
          description: Movie id
          example: 1
        name:
          type: string
          minLength: 1
          description: Movie name
          example: Inception
        year:
          type: integer
          minimum: 1900
          maximum: 2024
          description: Release year
          example: 2010
        rating:
          type: number
          description: Rating
          example: 7.5
  parameters: {}
paths:
  /:
    get:
      summary: Health Check
      responses:
        "200":
          description: Server is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server is running
  /movies:
    get:
      summary: Get all movies or filter by name
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
          description: Movie name to search for
      description: Retrieve a list of all movies. Optionally, provid a query parameter
        "name" to filter by a specific movie name
      responses:
        "200":
          description: List of Movies or a specific movie by name if the query param
            "name" is provided
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetMovieResponse"
        "404":
          description: Movie not found if the name is provided and does not match any movie
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status code
                    example: 404
                  error:
                    type: string
                    description: Error message
                    example: Movie not found
                required:
                  - status
                  - error
    post:
      summary: Create a new Movie
      description: Create a new Movie in the System
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMovieRequest"
      responses:
        "200":
          description: Movie created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateMovieResponse"
        "400":
          description: Invalid request body or validation error
        "409":
          description: Movie already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Conflict status code
                    example: 400
                  error:
                    type: string
                    description: Error message
                    example: Movie aldready exists
                required:
                  - status
                  - error
        "500":
          description: unexpected Error occured
  /movies/{id}:
    get:
      summary: Get a movie by Id
      description: Retrieve a single Movie by its unique Id
      parameters:
        - &a1
          name: id
          in: path
          required: true
          schema:
            type: string
          description: Movie ID
      responses:
        "200":
          description: Movie found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetMovieResponse"
        "404":
          description: Movie not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status code
                    example: 404
                  error:
                    type: string
                    description: Error message
                    example: Movie not found
                required:
                  - status
                  - error
    delete:
      summary: Delete a movie by Id
      description: Delete a movie by its Id
      parameters:
        - *a1
      responses:
        "200":
          description: Movie {id} has been deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status code
                    example: 200
                  message:
                    type: string
                    description: Success message for the deleted movie
                    example: Movie {id} has been deleted
                required:
                  - status
                  - message
        "404":
          description: Movie not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status code
                    example: 404
                  error:
                    type: string
                    description: Error message
                    example: Movie not found
                required:
                  - status
                  - error
        "500":
          description: Unexpected error occured
    put:
      summary: Update a movie by Id
      description: Update a movie by its id
      parameters:
        - *a1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMovieRequest"
      responses:
        "200":
          description: Movie updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdatedMovieResponse"
        "404":
          description: Movie not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    description: Response status code
                    example: 404
                  error:
                    type: string
                    description: Error message
                    example: Movie not found
                required:
                  - status
                  - error
        "500":
          description: Internal Server error
webhooks: {}
